In [29]:
import pandas as pd
from datetime import date
import numpy as np

In [30]:
deaths_csv = pd.read_csv("/Users/prajaktakulkarni/Desktop/Python/JHU_COVID_Deaths.csv")

In [31]:
counties_all = pd.read_csv("/Users/prajaktakulkarni/Desktop/Python/overall-county.csv")

In [32]:
deaths_csv.columns

Index(['FIPS', 'County', 'State', 'Population', 'Date', 'Deaths', 'DeathRate',
       'DeathRate1000'],
      dtype='object')

In [33]:
counties_all.columns

Index(['date', 'state_code', 'fips', 'gender', 'age_bucket', 'n', 'pct_cli',
       'pct_ili', 'pct_cli_anosmia_ageusia', 'pct_hh_cli',
       ...
       'pct_diabetes_weighted', 'pct_cancer_weighted',
       'pct_heart_disease_weighted', 'pct_high_blood_pressure_weighted',
       'pct_asthma_weighted', 'pct_chronic_lung_disease_weighted',
       'pct_kidney_disease_weighted', 'pct_autoimmune_disorder_weighted',
       'pct_no_above_medical_conditions_weighted',
       'pct_multiple_medical_conditions_weighted'],
      dtype='object', length=104)

In [34]:
counties_all['date']= pd.to_datetime(counties_all['date'])
deaths_csv['Date']= pd.to_datetime(deaths_csv['Date'])

In [35]:
counties_all = counties_all.sort_values(by=['fips','date'], ascending=True)

In [36]:
counties_all.gender.value_counts()

overall    67796
female     30111
male       11485
Name: gender, dtype: int64

In [37]:
counties_all.age_bucket.value_counts()

overall    85922
35-54       9332
55+         7853
18-34       6285
Name: age_bucket, dtype: int64

In [38]:
counties_filter = counties_all[counties_all.age_bucket == "overall"]
counties_filter = counties_filter[counties_filter.gender == "overall"]

In [39]:
counties_limited = counties_all

In [40]:
counties_limited.head()
#deaths_csv.head()

,date,state_code,fips,gender,age_bucket,n,pct_cli,pct_ili,pct_cli_anosmia_ageusia,pct_hh_cli,...,pct_diabetes_weighted,pct_cancer_weighted,pct_heart_disease_weighted,pct_high_blood_pressure_weighted,pct_asthma_weighted,pct_chronic_lung_disease_weighted,pct_kidney_disease_weighted,pct_autoimmune_disorder_weighted,pct_no_above_medical_conditions_weighted,pct_multiple_medical_conditions_weighted
41978,2020-04-07,al,1001,overall,overall,58,0.0,0.0,1.7241,0.0000,...,22.5362,8.8237,8.6917,33.3613,8.5199,4.6242,0.0000,3.9793,45.0044,22.5077
42798,2020-04-08,al,1001,overall,overall,58,0.0,0.0,0.0000,0.0000,...,11.5485,5.6571,4.0042,27.3263,10.3085,3.0151,2.1327,6.9741,46.3198,14.8178
43569,2020-04-09,al,1001,overall,overall,54,0.0,0.0,1.8868,1.8519,...,10.5565,8.6076,9.7792,33.8916,10.0756,13.1501,3.0079,9.5061,42.6598,29.9586
1,2020-04-06,al,1003,female,overall,56,0.0,0.0,3.5714,1.7857,...,6.2391,3.0230,8.1429,40.3764,24.2450,22.0205,1.6545,4.7447,35.6230,30.2314
41598,2020-04-06,al,1003,overall,overall,72,0.0,0.0,4.2857,1.3889,...,24.5611,1.8755,5.0519,45.9248,19.5381,18.7427,1.0265,5.0828,31.1653,38.0619

In [41]:
len(counties_limited.columns)

104

In [42]:
counties_a = counties_limited.merge(right = deaths_csv, left_on=['fips','date'], right_on=['FIPS','Date'],how = 'inner')

In [43]:
counties_a.to_csv("/Users/prajaktakulkarni/Desktop/Python/overall-county-dealth-all-columns.csv",index=False, na_rep= "")

In [44]:
df=pd.read_csv("/Users/prajaktakulkarni/Desktop/Python/overall-county-dealth-all-columns.csv")

In [45]:
df.tail()

,date,state_code,fips,gender,age_bucket,n,pct_cli,pct_ili,pct_cli_anosmia_ageusia,pct_hh_cli,...,pct_no_above_medical_conditions_weighted,pct_multiple_medical_conditions_weighted,FIPS,County,State,Population,Date,Deaths,DeathRate,DeathRate1000
109387,2020-04-08,wy,56025,overall,overall,82,1.2500,1.2500,3.7500,2.4691,...,52.9795,16.0197,56025,Natrona,Wyoming,79858,2020-04-08,0,0.0,0.0
109388,2020-04-09,wy,56025,female,overall,61,4.9180,4.9180,6.5574,6.5574,...,59.3852,19.8554,56025,Natrona,Wyoming,79858,2020-04-09,0,0.0,0.0
109389,2020-04-09,wy,56025,overall,overall,82,3.6585,3.6585,6.0976,4.8780,...,52.9794,27.2844,56025,Natrona,Wyoming,79858,2020-04-09,0,0.0,0.0
109390,2020-04-14,wy,56025,overall,overall,61,0.0000,0.0000,3.2787,0.0000,...,56.9198,11.8089,56025,Natrona,Wyoming,79858,2020-04-14,0,0.0,0.0
109391,2020-05-22,wy,56025,overall,overall,51,0.0000,0.0000,1.9608,0.0000,...,67.8050,19.0108,56025,Natrona,Wyoming,79858,2020-05-22,0,0.0,0.0

In [46]:
list(df.columns)

['date',
 'state_code',
 'fips',
 'gender',
 'age_bucket',
 'n',
 'pct_cli',
 'pct_ili',
 'pct_cli_anosmia_ageusia',
 'pct_hh_cli',
 'pct_cmnty_cli',
 'pct_hh_fever',
 'pct_hh_sore_throat',
 'pct_hh_cough',
 'pct_hh_shortness_of_breath',
 'pct_hh_difficulty_breathing',
 'mean_hh_cli_ct',
 'mean_cmnty_cli_ct',
 'pct_self_fever',
 'pct_self_cough',
 'pct_self_shortness_of_breath',
 'pct_self_difficulty_breathing',
 'pct_self_tiredness_or_exhaustion',
 'pct_self_nasal_congestion',
 'pct_self_runny_nose',
 'pct_self_muscle_joint_aches',
 'pct_self_sore_throat',
 'pct_self_persistent_pain_pressure_in_chest',
 'pct_self_nausea_vomiting',
 'pct_self_diarrhea',
 'pct_self_anosmia_ageusia',
 'pct_self_other',
 'pct_self_none_of_above',
 'pct_self_multiple_symptoms',
 'pct_tested_and_positive',
 'pct_tested_and_negative',
 'pct_tested_no_result',
 'pct_could_not_get_tested',
 'pct_did_not_try_to_get_tested',
 'pct_worked_outside_home',
 'pct_avoid_contact_all_or_most_time',
 'mean_outside_hh_contact_at_work_ct',
 'mean_outside_hh_contact_shopping_ct',
 'mean_outside_hh_contact_in_social_gatherings_ct',
 'pct_contact_covid_positive',
 'pct_diabetes',
 'pct_cancer',
 'pct_heart_disease',
 'pct_high_blood_pressure',
 'pct_asthma',
 'pct_chronic_lung_disease',
 'pct_kidney_disease',
 'pct_autoimmune_disorder',
 'pct_no_above_medical_conditions',
 'pct_multiple_medical_conditions',
 'pct_cli_weighted',
 'pct_ili_weighted',
 'pct_cli_anosmia_ageusia_weighted',
 'pct_hh_cli_weighted',
 'pct_cmnty_cli_weighted',
 'pct_hh_fever_weighted',
 'pct_hh_sore_throat_weighted',
 'pct_hh_cough_weighted',
 'pct_hh_shortness_of_breath_weighted',
 'pct_hh_difficulty_breathing_weighted',
 'mean_hh_cli_ct_weighted',
 'mean_cmnty_cli_ct_weighted',
 'pct_self_fever_weighted',
 'pct_self_cough_weighted',
 'pct_self_shortness_of_breath_weighted',
 'pct_self_difficulty_breathing_weighted',
 'pct_self_tiredness_or_exhaustion_weighted',
 'pct_self_nasal_congestion_weighted',
 'pct_self_runny_nose_weighted',
 'pct_self_muscle_joint_aches_weighted',
 'pct_self_sore_throat_weighted',
 'pct_self_persistent_pain_pressure_in_chest_weighted',
 'pct_self_nausea_vomiting_weighted',
 'pct_self_diarrhea_weighted',
 'pct_self_anosmia_ageusia_weighted',
 'pct_self_other_weighted',
 'pct_self_none_of_above_weighted',
 'pct_self_multiple_symptoms_weighted',
 'pct_tested_and_positive_weighted',
 'pct_tested_and_negative_weighted',
 'pct_tested_no_result_weighted',
 'pct_could_not_get_tested_weighted',
 'pct_did_not_try_to_get_tested_weighted',
 'pct_worked_outside_home_weighted',
 'pct_avoid_contact_all_or_most_time_weighted',
 'mean_outside_hh_contact_at_work_ct_weighted',
 'mean_outside_hh_contact_shopping_ct_weighted',
 'mean_outside_hh_contact_in_social_gatherings_ct_weighted',
 'pct_contact_covid_positive_weighted',
 'pct_diabetes_weighted',
 'pct_cancer_weighted',
 'pct_heart_disease_weighted',
 'pct_high_blood_pressure_weighted',
 'pct_asthma_weighted',
 'pct_chronic_lung_disease_weighted',
 'pct_kidney_disease_weighted',
 'pct_autoimmune_disorder_weighted',
 'pct_no_above_medical_conditions_weighted',
 'pct_multiple_medical_conditions_weighted',
 'FIPS',
 'County',
 'State',
 'Population',
 'Date',
 'Deaths',
 'DeathRate',
 'DeathRate1000']

In [47]:
df_policy= pd.read_csv('SMAK_us_state_fips_daily_policy.csv')

In [48]:
df_policy.head()

,date,state_code,fips,is_barrestrict,is_businesshealthsafety,is_caseisolation,is_emergdec,is_gathrecom,is_gathrestrict,is_nebusinessclose,is_otherbusinessclose,is_publicmask,is_quarantine,is_restaurantrestrict,is_schoolclose,is_schoolhealthsafety,is_stayathome,is_travelrestrictentry,is_travelrestrictexit,is_travelrestrictintra
0,2020-04-12,ak,2020,1,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,1
1,2020-04-12,ak,2150,1,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,1
2,2020-04-12,ak,2090,1,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,1
3,2020-04-12,ak,2130,1,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,1
4,2020-04-12,al,1005,1,1,1,1,0,1,0,1,0,0,1,1,0,1,0,0,0

In [49]:
df_symp_death_policy=df.merge(right = df_policy, left_on=['fips','date'], right_on=['fips','date'],how = 'inner')

In [50]:
df_symp_death_policy.tail()

,date,state_code_x,fips,gender,age_bucket,n,pct_cli,pct_ili,pct_cli_anosmia_ageusia,pct_hh_cli,...,is_otherbusinessclose,is_publicmask,is_quarantine,is_restaurantrestrict,is_schoolclose,is_schoolhealthsafety,is_stayathome,is_travelrestrictentry,is_travelrestrictexit,is_travelrestrictintra
100287,2020-05-20,wy,56021,overall,overall,57,0.0,0.0,3.5088,0.0000,...,1,1,1,1,1,1,0,0,0,0
100288,2020-05-31,wy,56021,overall,overall,51,2.0,0.0,2.0000,1.9608,...,1,1,1,1,1,1,0,0,0,0
100289,2020-06-02,wy,56021,overall,overall,56,0.0,0.0,5.3571,0.0000,...,1,1,1,1,1,1,0,0,0,0
100290,2020-04-14,wy,56025,overall,overall,61,0.0,0.0,3.2787,0.0000,...,1,1,1,1,1,0,0,0,0,0
100291,2020-05-22,wy,56025,overall,overall,51,0.0,0.0,1.9608,0.0000,...,1,1,1,1,1,1,0,0,0,0

In [51]:
df_symp_death_policy.to_csv("/Users/prajaktakulkarni/Desktop/Python/Counties_symp_death_policy.csv",index=False, na_rep= "")

In [52]:
df1= pd.read_csv('Counties_symp_death_policy.csv')

In [53]:
df1.tail()

,date,state_code_x,fips,gender,age_bucket,n,pct_cli,pct_ili,pct_cli_anosmia_ageusia,pct_hh_cli,...,is_otherbusinessclose,is_publicmask,is_quarantine,is_restaurantrestrict,is_schoolclose,is_schoolhealthsafety,is_stayathome,is_travelrestrictentry,is_travelrestrictexit,is_travelrestrictintra
100287,2020-05-20,wy,56021,overall,overall,57,0.0,0.0,3.5088,0.0000,...,1,1,1,1,1,1,0,0,0,0
100288,2020-05-31,wy,56021,overall,overall,51,2.0,0.0,2.0000,1.9608,...,1,1,1,1,1,1,0,0,0,0
100289,2020-06-02,wy,56021,overall,overall,56,0.0,0.0,5.3571,0.0000,...,1,1,1,1,1,1,0,0,0,0
100290,2020-04-14,wy,56025,overall,overall,61,0.0,0.0,3.2787,0.0000,...,1,1,1,1,1,0,0,0,0,0
100291,2020-05-22,wy,56025,overall,overall,51,0.0,0.0,1.9608,0.0000,...,1,1,1,1,1,1,0,0,0,0